### ISSUE TITLE
Declaring that an output format is not applicable

### ISSUE THREAD

**Issue by pfrenssen** [consolidation/output-formatters#59]
I am writing a Drush command that lists information about available search indexes. By definition this data will always be an array of data keyed by search index ID. It is not feasible to output this in a meaningful way with the `StringFormatter` so I'd like to have an option to not have this formatter available.

It's not clear to me how this can be achieved. I am using a customized version of the `RowsOfFields` data type called `RowsOfMultiValueFields`. It seems that currently I would have to hack `StringFormatter::isValidDataType()` to return FALSE if I am using `RowsOfMultiValueFields`. This doesn't seem like a good approach.

Would it perhaps be an idea to provide an `@allowed-formats` or `@disallowed-formats` annotation for commands?

What would also work for me is that I could declare my data type in my data type class:

```
    protected function defaultOptions()
    {
        return [
            FormatterOptions::DATA_TYPE => 'array',
        ] + parent::defaultOptions();
    }
```

**Comment by greg-1-anderson** [comment]
Now StringTransformationInterface is available for data structures to declare that they can be converted to strings. The problem is that the string formatter tries to convert any object to tsv; this may or may not succeed.

It would be a breaking change to remove the automatic conversion to tsv, but this would probably be worth doing the next time we bump the major version here. It would also be useful if StringTransformationInterface had a method to declare whether the data type was convertable to a string or not, so that this facility could be overridden, or dynamically determined.

**Comment by greg-1-anderson** [comment]
I've been thinking about this a bit more.

For commands that output data types that can *sometimes* be converted to `string`, it is sufficient to implement StringTransformationInterface, and throw an exception if the data cannot be converted. `string` will still be listed as an available format.

For commands that produce data that can *never* be converted to a string, it's a bit more complicated.  The issue is that `isValidDataType` takes as a parameter only the *type* of the data format produced by the command. The API is this way because we need to know whether to put the `string` format in the list of valid formats in the help output, and there is no specific output object available at the time that `help` is running. The best thing I can think of is to use a marker interface to indicate that an output type can or can not be converted to a string. We'd have to pick just one of those. The thing about this, though, is that it would be difficult for a subclass of a data type to change the disposition of this decision if one of its parent classes implements the interface.

One thing I would recommend is using the new `UnstructuredListData` data type here. This data type usually cannot be converted to a string. If you subclass from this data type, then you'll benefit from any enhancements we make to this class vis-a-vis applicability of the string output format.

Also, I forgot to mention that I do not like the annotation solution much, as it requires everyone who uses the output data type to annotate their command correctly. The general design for output formatters is that a class only needs to declare the data type that it produces, and each formatter should then correctly determine whether or not it can process that type.
